### ISSUE TITLE
Method used for spawning from Sk is deprecated

### ISSUE THREAD

**Issue by lalomartins** [AgogLabs/SkookumScript-UnrealEngine#11]
TIL `BeginSpawningActorFromClass` is deprecated, according to [the docs](https://api.unrealengine.com/INT/API/Runtime/Engine/Kismet/UGameplayStatics/BeginSpawningActorFromClass/index.html). 

This is the definition of `Actor.spawn_at_xform`:

```SkookumScript
( Transform xform
  Actor     owner: Actor!null
  World     world_context: @@world
) ThisClass_

  [
  !actor: GameLib.begin_spawning_actor_from_class(
    world_context static_class xform false owner)
  GameLib.finish_spawning_actor(actor xform)
  ]
```

Looking at the source code for that in the UnrealEngine repo, it seems it just converts the `bool bNoCollisionFail` argument to a `ESpawnActorCollisionHandlingMethod`, then chains to `BeginDeferredActorSpawnFromClass`. To be future-proof, `spawn_at_xform` should probably do the same, passing `ESpawnActorCollisionHandlingMethod.@@always_spawn` as the `collision_handling_override` argument.

**Comment by error454** [comment]
This is absolutely correct. Thanks for the note.

**Comment by error454** [comment]
Fixed in https://github.com/AgogLabs/SkookumScript-UnrealEngine/commit/e692e6014216c051a78faabb01e1e7c745bc9899.
