### ISSUE TITLE
EBuildModuleType Type enums were renamed in 4.12

### ISSUE THREAD

**Issue by flipswitchingmonkey** [AgogLabs/SkookumScript-UnrealEngine#4]
Not so much an issue as more of a heads up: starting with the 4.12 branch UE has renamed the enums in the EBuildModuleType struct at UnrealEngine/Engine/Source/Programs/UnrealHeaderTool/Public/IScriptGeneratorPluginInterface.h, so now the compilation of SkookumScript-UnrealEngine/Source/SkookumScriptGenerator/Private/SkookumScriptGenerator.cpp will fail.

Also for some reason neither the ..\..\Plugins\SkookumScript\Source\SkookumScriptGenerator nor ..\..\Plugins\SkookumScript\Source\SkookumScriptGenerator\Private made it into the UE4 project file include paths in my case.

**Comment by pluranium** [comment]
Thanks for the heads up - we will look into this asap.

**Comment by flipswitchingmonkey** [comment]
They also changed the definition of Throwf in \Source\Runtime\Core\Public\Misc\OutputDevice.h
